### ISSUE TITLE
Error building kernel

### ISSUE THREAD

**Issue by hxrofo** [silont-project/kernel_xiaomi_sdm439#1]
Hello
I'm trying to build the kernel for Kali Nethunter on a Redmi 8 (olive). However, I keep getting these errors:
`In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:95:
In file included from ../include/trace/trace_events.h:707:
../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats'
                __entry->pl             = rq->walt_stats.pred_demands_sum;
                                          ~~~~~~~~~~~~~~ ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:95:
In file included from ../include/trace/trace_events.h:707:
../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
                __entry->util_avg_walt = ((struct ravg*)_ravg)->demand /
                ~~~~~~~  ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:95:
In file included from ../include/trace/trace_events.h:707:
../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
                __entry->util_avg = __entry->util_avg_walt;
                                    ~~~~~~~  ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:96:
In file included from ../include/trace/perf.h:89:
../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats'
                __entry->pl             = rq->walt_stats.pred_demands_sum;
                                          ~~~~~~~~~~~~~~ ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:96:
In file included from ../include/trace/perf.h:89:
../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
                __entry->util_avg_walt = ((struct ravg*)_ravg)->demand /
                ~~~~~~~  ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
In file included from ../kernel/sched/core.c:65:
In file included from ../include/trace/events/sched.h:1870:
In file included from ../include/trace/define_trace.h:96:
In file included from ../include/trace/perf.h:89:
../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
                __entry->util_avg = __entry->util_avg_walt;
                                    ~~~~~~~  ^
../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
#define TP_fast_assign(args...) args
                                ^~~~
../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
                             PARAMS(assign),                   \
                                    ^~~~~~
../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
#define PARAMS(args...) args
                        ^~~~
../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
        { assign; }                                                     \
          ^~~~~~
6 errors generated.
make[3]: *** [../scripts/Makefile.build:342: kernel/sched/core.o] Error 1
make[2]: *** [../scripts/Makefile.build:656: kernel/sched] Error 2
make[1]: *** [/root/Desktop/nethunter/sakura/Makefile:1158: kernel] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      mm/showmem.o
  CC      mm/vmpressure.o
  CC      mm/init-mm.o

**How can I fix this? Thanks`**

**Comment by Chuck439** [comment]
actually i don't know much about nethunter and main branch can be compiled using GCC only. Maybe try a11/lineageos branch for that

**Comment by Firmank123** [comment]
> Hello
> I'm trying to build the kernel for Kali Nethunter on a Redmi 8 (olive). However, I keep getting these errors:
> `In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:95:
> In file included from ../include/trace/trace_events.h:707:
> ../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats'
> __entry->pl = rq->walt_stats.pred_demands_sum;
> ~~~~~~~~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:95:
> In file included from ../include/trace/trace_events.h:707:
> ../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
> __entry->util_avg_walt = ((struct ravg*)_ravg)->demand /
> ~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:95:
> In file included from ../include/trace/trace_events.h:707:
> ../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
> __entry->util_avg = __entry->util_avg_walt;
> ~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:96:
> In file included from ../include/trace/perf.h:89:
> ../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats'
> __entry->pl = rq->walt_stats.pred_demands_sum;
> ~~~~~~~~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:96:
> In file included from ../include/trace/perf.h:89:
> ../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
> __entry->util_avg_walt = ((struct ravg*)_ravg)->demand /
> ~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> In file included from ../kernel/sched/core.c:65:
> In file included from ../include/trace/events/sched.h:1870:
> In file included from ../include/trace/define_trace.h:96:
> In file included from ../include/trace/perf.h:89:
> ../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task'
> __entry->util_avg = __entry->util_avg_walt;
> ~~~~~~~ ^
> ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign'
> #define TP_fast_assign(args...) args
> ^~~~
> ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT'
> PARAMS(assign),
> ^~~~~~
> ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS'
> #define PARAMS(args...) args
> ^~~~
> ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS'
> { assign; }
> ^~~~~~
> 6 errors generated.
> make[3]: *** [../scripts/Makefile.build:342: kernel/sched/core.o] Error 1
> make[2]: *** [../scripts/Makefile.build:656: kernel/sched] Error 2
> make[1]: *** [/root/Desktop/nethunter/sakura/Makefile:1158: kernel] Error 2
> make[1]: *** Waiting for unfinished jobs....
> CC mm/showmem.o
> CC mm/vmpressure.o
> CC mm/init-mm.o
> 
> **How can I fix this? Thanks`**

actually i don't know about nethunter and main branch can be compiled using GCC only. Use a11/lineageos branch for that
Also, are you changing PELT to WALT?

**Comment by NunuChan123** [comment]
> Hello I'm trying to build the kernel for Kali Nethunter on a Redmi 8 (olive). However, I keep getting these errors: `In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:95: In file included from ../include/trace/trace_events.h:707: ../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats' __entry->pl = rq->walt_stats.pred_demands_sum; ~~~~~~~~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:95: In file included from ../include/trace/trace_events.h:707: ../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task' __entry->util_avg_walt = ((struct ravg*)_ravg)->demand / ~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:95: In file included from ../include/trace/trace_events.h:707: ../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task' __entry->util_avg = __entry->util_avg_walt; ~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/trace_events.h:686:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:96: In file included from ../include/trace/perf.h:89: ../include/trace/events/sched.h:589:33: error: no member named 'pred_demands_sum' in 'struct walt_sched_stats' __entry->pl = rq->walt_stats.pred_demands_sum; ~~~~~~~~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:96: In file included from ../include/trace/perf.h:89: ../include/trace/events/sched.h:1402:12: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task' __entry->util_avg_walt = ((struct ravg*)_ravg)->demand / ~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ In file included from ../kernel/sched/core.c:65: In file included from ../include/trace/events/sched.h:1870: In file included from ../include/trace/define_trace.h:96: In file included from ../include/trace/perf.h:89: ../include/trace/events/sched.h:1404:32: error: no member named 'util_avg_walt' in 'struct trace_event_raw_sched_load_avg_task' __entry->util_avg = __entry->util_avg_walt; ~~~~~~~ ^ ../include/trace/trace_events.h:653:33: note: expanded from macro 'TP_fast_assign' #define TP_fast_assign(args...) args ^~~~ ../include/trace/trace_events.h:64:16: note: expanded from macro 'TRACE_EVENT' PARAMS(assign), ^~~~~~ ../include/linux/tracepoint.h:88:25: note: expanded from macro 'PARAMS' #define PARAMS(args...) args ^~~~ ../include/trace/perf.h:65:4: note: expanded from macro 'DECLARE_EVENT_CLASS' { assign; } ^~~~~~ 6 errors generated. make[3]: *** [../scripts/Makefile.build:342: kernel/sched/core.o] Error 1 make[2]: *** [../scripts/Makefile.build:656: kernel/sched] Error 2 make[1]: *** [/root/Desktop/nethunter/sakura/Makefile:1158: kernel] Error 2 make[1]: *** Waiting for unfinished jobs.... CC mm/showmem.o CC mm/vmpressure.o CC mm/init-mm.o
> 
> **How can I fix this? Thanks`**

Hi did you managed to build the kernel? I am trying to build kernel to install nethunter in my Redmi 8. But with the lack of experience I am stuck
